name: publish

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --python 3.12 --dev

      - name: Lint with flake8
        run: |
          pipenv run flake8 . --count --show-source --statistics
          pipenv run flake8 . --count --exit-zero --statistics

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5

      - name: Generate distribution 📦for PyPI
        run: |
          pip install wheel
          python setup.py sdist bdist_wheel

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
